In [5]:
import pandas as pd
import sqlite3
import numpy as np
import matplotlib as plt
from sklearn import metrics
from datetime import datetime
import xgboost as xgb
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.base import TransformerMixin
from sklearn.model_selection import train_test_split
from matplotlib import pylab as plt

In [2]:
train=pd.read_csv('train.csv')

In [3]:
train

,id,XINGBIE,CSNY,HYZK,ZHIYE,ZHICHEN,ZHIWU,XUELI,DWJJLX,DWSSHY,...,GRZHZT,GRZHYE,GRZHSNJZYE,GRZHDNGJYE,GRYJCE,DWYJCE,DKFFE,DKYE,DKLL,label
0,train_0,1,1038672000,90,90,999,0,99,150,12,...,1,3223.515,801.310,837.000,312.00,312.00,175237,154112.935,2.708,0
1,train_1,2,504892800,90,90,999,0,99,110,0,...,1,18055.195,53213.220,1065.200,795.84,795.84,300237,298252.945,2.979,0
2,train_2,1,736185600,90,90,999,0,99,150,9,...,1,27426.600,13963.140,7230.020,1444.20,1444.20,150237,147339.130,2.708,0
3,train_3,1,428515200,90,90,999,0,99,150,7,...,1,111871.130,99701.265,2271.295,1417.14,1417.14,350237,300653.780,2.708,0
4,train_4,2,544204800,90,90,999,0,99,900,14,...,1,237.000,11028.875,35.780,325.50,325.50,150237,145185.010,2.708,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,train_39995,1,573148800,90,90,999,0,99,110,16,...,1,82865.575,65304.370,4026.600,590.76,590.76,150237,117816.680,2.708,0
39996,train_39996,2,57772800,90,90,999,0,99,110,14,...,1,32811.585,27065.150,1603.560,407.82,407.82,300237,267615.065,2.979,0
39997,train_39997,2,673023600,90,90,999,0,99,143,9,...,1,8875.695,1309.890,3185.800,605.60,605.60,175237,237.000,2.708,0
39998,train_39998,1,536428800,90,90,999,0,99,150,6,...,1,2079.400,252.875,1614.490,467.30,467.30,125237,113068.900,2.708,1
39999,train_39999,1,31507200,90,90,999,0,99,110,14,...,1,26210.635,27266.080,-4994.610,800.70,800.70,300237,287737.000,2.979,0

In [10]:
# b1 贷款余额比缴存余额
train['b1']=train['DKYE']/train['GRZHYE']

# b2 个人账户上年结转余额比个人账户余额
train['b2']=train['GRZHSNJZYE']/train['GRZHYE']

# b3 个人账户当年归集余额比个人账户余额
train['b3']=train['GRZHDNGJYE']/train['GRZHYE']

# b4 个人缴存额比个人账户余额
train['b4']=train['GRYJCE']/train['GRZHYE']

# b5 单位缴存额比个人账户余额
train['b5']=train['DWYJCE']/train['GRZHYE']

# b6 个人缴存额加单位缴存额
train['b6']=train['GRYJCE']+train['DWYJCE']

#b7 总缴存额比个人账户余额
train['b7']=train['b6']/train['GRZHYE']

# b8 个人缴存额比单位缴存额
train['b8']=train['GRYJCE']/train['DWYJCE']

# b9 个人缴存余额比贷款余额
train['b9']=train['GRYJCE']/train['DKYE']

# b10 单位缴存余额比贷款余额
train['b10']=train['DWYJCE']/train['DKYE']

# b11 贷款余额比个人账户余额
train['b11']=train['DKYE']/train['GRZHYE']

SyntaxError: invalid syntax (<ipython-input-10-8b863cc6ff8d>, line 20)

0        18605
1        18605
2        18605
3        18605
4        18605
         ...
39995    18605
39996    18605
39997    18605
39998    18605
39999    18605
Name: age, Length: 40000, dtype: int64